### ISSUE TITLE
InputNumber component problems

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#260]
I'm not sure how the `InputNumber` component is suppose to work. But if my following observation looks proper enough, then the component needs a lots of fix.

## 1
- Drag an 'InputNumber' component to the stage
- Dragged component has no text inside it
- Type something in the 'Value' editor field - you can input even String characters [Bug]

## 2
- Drag an 'InputNumber' component to the stage
- Dragged component has no text inside it
- Type something in the 'Value' editor field - this time input random numbers
- Dragged component starts showing value separated by comma (in my case)
![image](https://user-images.githubusercontent.com/24370870/39989996-232f1e38-5789-11e8-9ac7-525b57318605.png)
- [Question] Is these commas or separators suppose to shown like this when there no 'Decimal Separator Char' or 'Thousand Separator Char' provided?

## 3
- Remove all the entered value from 'Value' editor field
- Dragged component shows "0.00" - this was showing blank before [Bug]

## 4
- Starts typing some random digits again int he 'Value' editor field
- After a length of digit entered cursor showing placed somewhere middle in the entered value, but not at the end [Bug]

## 5
- Have some value entered through 'Value' field
- Change values to 'Decimal Separator Char' or 'Thousand Separator Char'
- Nothing changed to the dragged component text on the stage [Bug]

## 6
- Drag a new 'InputNumber' component to the stage
- Change values to 'Decimal Separator Char' and 'Thousand Separator Char'
- Change values to 'Value'
- Dragged component text shows "0.00" but no effect of entered 'Value' text [Bug]

**Comment by rat-moonshine** [comment]
Against 1, all the editor TextForm can be restricted with 0-9:
`<forms:TextForm label="Value" textProperty="text" restrict="0-9"/>`

**Comment by piotrzarzycki21** [comment]
Please number 1 raise as a separate issue.

**Comment by piotrzarzycki21** [comment]
In case of **2** - Yes comma are expected - Look into the PrimeFaces [inputNumber](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml) - Try to type long number in input **Custom decimal places**

**Comment by piotrzarzycki21** [comment]
I can take a look and see what can I do with that control.

**Comment by rat-moonshine** [comment]
Number 1 can be handled easily I don't think this needs to raise separately. I have pushed with 'restrict' changes to the edit fields.

**Comment by JoelProminic** [comment]
Reviewing @rat-moonshine's original complaints:
1. The value is restricted to numbers only.  However, this means it is impossible to enter a number like 3.14, even though there is a decimal separator.
2. The "Thousand separator char" seems to work fine.
3. The controll still shows 0.00 after the value is cleared
4. Doesn't seem to trigger anymore
5. The "separator char" fields also restrict the values to integers only, so I can't test changing he separators to a reasonable value.   I tried changing the "Thousand separator char" to "2", but the displayed string did not change
6. Cannot test

**Comment by piotrzarzycki21** [comment]
@JoelProminic I did push for those restriction fixes. You have to pull the newest version from Bamboo. I think I did it 1 hour before your comment. I will be working farther on the rest of the points.

**Comment by piotrzarzycki21** [comment]
> ## 1
> - Drag an 'InputNumber' component to the stage
> - Dragged component has no text inside it
> - Type something in the 'Value' editor field - you can input even String characters [Bug]

It should be fixed. Restriction to the Value field has been added.


> ## 2
> - Drag an 'InputNumber' component to the stage
> - Dragged component has no text inside it
> - Type something in the 'Value' editor field - this time input random numbers
> - Dragged component starts showing value separated by comma (in my case)
> ![image](https://user-images.githubusercontent.com/24370870/39989996-232f1e38-5789-11e8-9ac7-525b57318605.png)
> - [Question] Is these commas or separators suppose to shown like this when there no 'Decimal Separator Char' or 'Thousand Separator Char' provided?


If you remove Thousand separator there should not be any comas in the field - That's fixed. If you remove decimal separator it will be replaced by default by "." (dot) - PrimeFaces input number behaves like that. Even if you have `<p:inputNumber  thousandSeparator="" decimalSeparator=""/>` input will allow for dots and display it for the numbers. 

> ## 3
> - Remove all the entered value from 'Value' editor field
> - Dragged component shows "0.00" - this was showing blank before [Bug]

PrimeFaces inputNumber is showing as default 0.00, so we are also trying to mimic that.

> ## 4
> - Starts typing some random digits again int he 'Value' editor field
> - After a length of digit entered cursor showing placed somewhere middle in the entered value, but not at the end [Bug]

I'm not sure how to reproduce that one - If you still will be able to reproduce it after my changes, please record some short gif.

> ## 5
> - Have some value entered through 'Value' field
> - Change values to 'Decimal Separator Char' or 'Thousand Separator Char'
> - Nothing changed to the dragged component text on the stage [Bug]

Fixed.

> ## 6
> - Drag a new 'InputNumber' component to the stage
> - Change values to 'Decimal Separator Char' and 'Thousand Separator Char'
> - Change values to 'Value'
> - Dragged component text shows "0.00" but no effect of entered 'Value' text [Bug]

Should be fixed.

**Comment by rat-moonshine** [comment]
Having latest source from Git, I gave some tests. Following were my findings:

1. Seems good to me

2. Thank you for the explanation, I have found another related bug, though. Please read follows. 

3. Okay

4. I didn't found this problem anymore, either

5. Seems good 

6. I remember I able to reproduce this related problem for once - but I couldn't able to reproduce this once more. I would suggest to keep an watch to this, though.

Some other bugs:

## 1
- Drag an 'InputNumber' component to the stage
- Remove everything from 'Decimal separator char' and 'Thousand separator char' fields
- Select 'Value' field and enter something like 1234567890
- Return to 'Decimal separator char' and input a comma (,) and hit Enter
- 'Value' and the editor's Input Text value cleared
- The above is also true for 'Thousand separator char'

##2
![ve35_1](https://user-images.githubusercontent.com/24370870/40978770-ae5e77fa-68f1-11e8-8666-c4630cb61444.gif)

**Comment by piotrzarzycki21** [comment]
> Return to 'Decimal separator char' and input a comma (,) and hit Enter

Did you end up with situation where Thousand and Decimal separator were comma "," ?

**Comment by piotrzarzycki21** [comment]
I'm able to reproduce ## 1, so working on fix.

**Comment by piotrzarzycki21** [comment]
Issue **1** has been fixed. I will be looking into **2** tomorrow.

**Comment by atinprominic** [comment]
I tested all the 6 bugs reported and all of them are fixed as per my testing.

**Comment by piotrzarzycki21** [comment]
I have extracted issue 2, because it is required much more time to handle that, if it is even will be possible in Flex.

**Comment by JoelProminic** [comment]
When I did these steps:
1. Open a Visual Editor
2. Add an inputNumber control
3. Set the ID to "testInput"
4. Hit Enter

I got this error:

    : Error #1009
    : TypeError: Error #1009
    : 	at view.primeFaces.forms::BasicsForm/onIdUpdated()
    : 	at MethodInfo-26246()
    : 	at mx.binding.utils::ChangeWatcher/wrapHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at view.primeFaces.surfaceComponents.components::InputNumber/set idAttribute()
    : 	at view.primeFaces.forms::BasicsForm/commitId()
    : 	at view.primeFaces.forms::BasicsForm/idInput_keyDownHandler()
    : 	at view.primeFaces.forms::BasicsForm/__idTextInput_keyDown()
    :
    : Click here to Report a Bug

I didn't notice any problems related to this error, though.


The Value, Decimal separator char, and Thousand separator char feel a little uncomfortable to use currently, but they seem to work.  For and example of the problematic behavior:
1. I want to change the Decimal separator to ',' and the thousand separator to a ' ' (I have seen this format used elsewhere)
2. I enter 1000.00 for Value.  It changes to 1,000.00 (which is good)
3. I change Decimal separator char to ",".  PROBLEM:  Value clears
4. I change Thousand separator char to ' '.  The value resets to "0,00"

If I reverse steps 3 and 4, then Value is not cleared.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have just pushed fix for `: Error #1009` - Pickup new Bamboo version once it's rebuild. As for the second issue I will look into that next week. That's not a blocking. Probably will raise separate issue for that.

**Comment by JoelProminic** [comment]
I confirmed that the error is cleared.   I agree, the other behavior I reported does not need to block the release, and it is a low priority.

**Comment by piotrzarzycki21** [comment]
> The Value, Decimal separator char, and Thousand separator char feel a little uncomfortable to use currently, but they seem to work. For and example of the problematic behavior:
> 
> I want to change the Decimal separator to ',' and the thousand separator to a ' ' (I have seen this format used elsewhere)
> I enter 1000.00 for Value. It changes to 1,000.00 (which is good)
> I change Decimal separator char to ",". PROBLEM: Value clears
> I change Thousand separator char to ' '. The value resets to "0,00"
> If I reverse steps 3 and 4, then Value is not cleared.

The default value for decimal separator is ".". Even if you won't provide it InputNumber in PrimeFaces display that separator. If you type following number in pure PrimeFaces InpuNumber "10000" you will get "10000.00". I just pushed changes which make sure that you won't be able to leave that field empty.

**Comment by JoelProminic** [comment]
When I tried the value "10000" with the default settings, I got "10,000" (no decimal point or extra digits).

When I retried my earlier procedure, I found that I could not change the value of "Decimal separator char" to ','.  The only allowed characters are '.' and numbers.  This limitation makes it a bit pointless to provide the "Decimal separator char" option.  (Choosing a number separator clears the error as in my original error, but it doesn't make sense to choose a number separator anyway.)

To clarify my original procedure, I entered a space character rather than an empty string in the step below:  

> 4. I change Thousand separator char to ' '. The value resets to "0,00"

This is still an obscure, low-priority bug, so don't spend too much time on this.

**Comment by piotrzarzycki21** [comment]
> When I tried the value "10000" with the default settings, I got "10,000" (no decimal point or extra digits).

I know, but after export you will have 10000.00 - I'm not sure whether I will be able to mimic that behavior in Flex.

I will look into the issue with inability to type other characters

**Comment by piotrzarzycki21** [comment]
> When I retried my earlier procedure, I found that I could not change the value of "Decimal separator char" to ','. The only allowed characters are '.' and numbers. This limitation makes it a bit pointless to provide the "Decimal separator char" option.

I have fixed above issue. I'm sorry about that!

**Comment by piotrzarzycki21** [comment]
> To clarify my original procedure, I entered a space character rather than an empty string in the step below:

I took over this one as well.
