### ISSUE TITLE
Add unit tests to all components in VisualEditorConverterLib

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#435]
We should add at least basic tests to all components as a continuation of #428. First tests can be found [here](https://github.com/prominic/VisualEditorConverterLib/blob/master/libTests/src/unitTests/AllTestsSuite.as)

Following components should contains testes:
- [x] Div (@piotrzarzycki21)
- [x] RootDiv (@piotrzarzycki21)
- [x] OutputLabel (@rat-moonshine )
- [x] InputText (@rat-moonshine )
- [x] Button (@piotrzarzycki21)
- [x] InputMask (@piotrzarzycki21)
- [x] InputNumber (@rat-moonshine )
- [x] InputTextarea (@rat-moonshine )
- [x] TextEditor (@rat-moonshine )
- [x] SelectedBooleanCheckbox (@rat-moonshine )
- [x] SelectOneRadio (@rat-moonshine )
- [x] SelectOneMenu (@rat-moonshine )
- [x] SelectOneListbox (@piotrzarzycki21)
- [x] AutoComplete (@piotrzarzycki21)
- [x] TabView (@rat-moonshine )
- [x] Tree (@rat-moonshine )
- [x] DataTable (@piotrzarzycki21)
- [x] Fieldset (@piotrzarzycki21)
- [x] Include (@rat-moonshine )
- [x] Grid (@piotrzarzycki21)
- [x] PanelGrid (@piotrzarzycki21)
- [x] Calendar (@piotrzarzycki21)

**How unit tests helps:**
1. We will be able to check whether our conversion went good without running [XHTMLConverterCLI](https://github.com/prominic/XHTMLConverterCLI)
2. Appropriate tests cases makes sure that components can consume current format of Visual Editor XML
3. Tests validate whether input is being properly parsed to components properties
4. Tests "ask" you if they fail - Do I need that change ? Does my change are properly implemented ? 
5. Tests may validate xHTML output and compare to VE XML input

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 please document the process-break to how to this unit-test, and what are its advantages (per the process way).

**Comment by piotrzarzycki21** [comment]
Yes I was going to do this soon.

**Comment by piotrzarzycki21** [comment]
> please document the process-break to how to this unit-test, 

@rat-moonshine I have added some points to description - let me know if it's convinced you. Apart of that what do you mean in above sentence ? What do you want to know more ? 
More information how tests are working now:
1. Unit tests project is placed [here](https://github.com/prominic/VisualEditorConverterLib/tree/master/libTests). Unfortunately Moonshine is not able to run unit tests (which we definitely should improve), so in order to run them you have to configure project using FB or Intellij.
2. Almost each added so far tests is a Parameterized test - it means that when we are running some test method ex. [buttonPropertiesTest](https://github.com/prominic/VisualEditorConverterLib/blob/14a60cf23973ff837e83a76fbe703dad2e03aa4c/libTests/src/unitTests/button/ButtonTest.as#L80) we are injecting data which are used for proper component testing. - In our case those data will be Visual Editor XML.
3. Each tests contains [special loader](https://github.com/prominic/VisualEditorConverterLib/blob/14a60cf23973ff837e83a76fbe703dad2e03aa4c/libTests/src/unitTests/button/ButtonTest.as#L46) which takes as a first parameter - name of the test case file and name of test class.
4. Loader reads [test case](https://github.com/prominic/VisualEditorConverterLib/blob/master/libTests/src/examples/button/button.xml) and load appropriate input. As you can see you can have as many tests cases for one test as you want. Button for example [have two](https://github.com/prominic/VisualEditorConverterLib/tree/master/libTests/src/examples/button/tests).
Screenshot which showing that button's tests has been run two times, because of amount of tests cases.
![testcase](https://user-images.githubusercontent.com/24554795/50593138-68a4eb80-0e97-11e9-9359-ecaba8aa94f1.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I forgot to mention that in order to run unit tests you have to add path to source folder in this class: [TestConfig.as](https://github.com/prominic/VisualEditorConverterLib/blob/master/libTests/src/config/TestConfig.as) - Ex: `public var baseURL:String = "D:\\VisualEditorConverterLib\\libTests\\src";`

**Comment by rat-moonshine** [comment]
VisualEditorConverterLib Ant build process thrown me following error when ran on Windows:

```
copy-bin-to-xhtmlconvertercli:
     [echo] Copying VisualEditorConverterLib-0.1.0.swc to ../XHTMLConverterCLI/libs
     [copy] Copying 1 file to G:\DevareaLocal\Prominic\Prominic_Git\git\XHTMLConverterCLI\libs

test:
    [mxmlc] Loading configuration file G:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR_28.0\frameworks\flex-config.xml
    [mxmlc] G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin\FlexUnitApplication.swf (688966 bytes)
 [flexunit] Validating task attributes ...
 [flexunit] Generating default values ...
 [flexunit] Using default working dir [G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib]
 [flexunit] Using the following settings for the test run:
 [flexunit]     FLEX_HOME: [G:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR_28.0]
 [flexunit]     haltonfailure: [true]
 [flexunit]     headless: [false]
 [flexunit]     display: [99]
 [flexunit]     localTrusted: [true]
 [flexunit]     player: [flash]
 [flexunit]     port: [8765]
 [flexunit]     swf: [G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin\FlexUnitApplication.swf]
 [flexunit]     timeout: [60000ms]
 [flexunit]     toDir: [G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin]
 [flexunit] Setting up server process ...
 [flexunit] Entry [G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin] already available in local trust file at [C:\Users\Santanu\AppData\Roaming\Macromedia\Flash Player\#Security\FlashPlayerTrust\flexUnit.cfg].
 [flexunit] Starting server ...
 [flexunit] Executing 'rundll32' with arguments:
 [flexunit] 'url.dll,FileProtocolHandler'
 [flexunit] 'G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin\FlexUnitApplication.swf'
 [flexunit]
 [flexunit] The ' characters around the executable and arguments are
 [flexunit] not part of the command.
 [flexunit]
 [flexunit]
 [flexunit] Stopping server ...
 [flexunit] End of test data reached, sending acknowledgement to player ...
 [flexunit] Closing client connection ...
 [flexunit] Closing server on port [8765] ...

BUILD FAILED
G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\build.xml:56: java.util.concurrent.ExecutionException: error receiving report from flexunit
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.flexunit.ant.tasks.TestRun.run(Unknown Source)
        at org.flexunit.ant.tasks.FlexUnitTask.execute(Unknown Source)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:834)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: error receiving report from flexunit
        at org.flexunit.ant.FlexUnitSocketThread.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Address already in use: JVM_Bind
        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at java.net.ServerSocket.<init>(ServerSocket.java:128)
        at org.flexunit.ant.FlexUnitSocketServer.openServerSocket(Unknown Source)
        at org.flexunit.ant.FlexUnitSocketServer.start(Unknown Source)
        ... 5 more

Total time: 6 seconds
```

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Can you [change port](https://github.com/prominic/VisualEditorConverterLib/blob/1afe24256daa9370ab5b229026b307bd119750b1/build.xml#L56) which is used for run tests ? When you double click in your system on any swf does it run as Flash Player projector?

**Comment by piotrzarzycki21** [comment]
Is it possible that you have situation that your Flash Builder blocking that port cause you have run previously some tests session ?

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 my apology, I should had look more closely on the requirement - once downloaded the flash player file, and associate the .swf (manually)to open with, I able to have different output this time. I also closed the Flash Builder to overcome any possible port-usage problem. 

This time, I have different results, but it seems like the process failed to feed the tests with correct example XML paths:

```
[flexunit] Setting up server process ...
 [flexunit] Starting server ...
 [flexunit] Entry [G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin] already available in local trust file at [C:\Users\ratMoonshine\AppData\Roaming\Macromedia\Flash Player\#Security\FlashPlayerTrust\flexUnit.cfg].
 [flexunit] Opening server socket on port [8765].
 [flexunit] Executing 'rundll32' with arguments:
 [flexunit] 'url.dll,FileProtocolHandler'
 [flexunit] 'G:\DevareaLocal\Prominic\Prominic_Git\git\VisualEditorConverterLib\libTests\bin\FlexUnitApplication.swf'
 [flexunit]
 [flexunit] The ' characters around the executable and arguments are
 [flexunit] not part of the command.
 [flexunit]
 [flexunit] Waiting for client connection ...
 [flexunit] Client connected.
 [flexunit] Setting inbound buffer size to [262144] bytes.
 [flexunit] Receiving data ...
 [flexunit] Sending acknowledgement to player to start sending test data ...
 [flexunit]
 [flexunit] FlexUnit test initializationError in suite unitTests.autoComplete.AutoCompleteTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.selectOneListbox.SelectOneListboxTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.dataTable.DataTableTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.converter.ConverterTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.outputLabel.OutputLabelTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.inputText.InputTextTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.button.ButtonTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.inputTextarea.InputTextareaTest had errors.
 [flexunit] FlexUnit test initializationError in suite unitTests.calendar.CalendarTest had errors.
 [flexunit]
 [flexunit] Stopping server ...
 [flexunit] End of test data reached, sending acknowledgement to player ...
 [flexunit] Closing client connection ...
 [flexunit] Closing server on port [8765] ...
 [flexunit] Analyzing reports ...
 [flexunit]
 [flexunit] Suite: unitTests.inputTextarea.InputTextareaTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec
 [flexunit] Suite: unitTests.autoComplete.AutoCompleteTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec
 [flexunit] Suite: unitTests.inputText.InputTextTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
 [flexunit] Suite: unitTests.dataTable.DataTableTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
 [flexunit] Suite: unitTests.outputLabel.OutputLabelTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
 [flexunit] Suite: unitTests.calendar.CalendarTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
 [flexunit] Suite: unitTests.converter.ConverterTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
 [flexunit] Suite: unitTests.selectOneListbox.SelectOneListboxTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec
 [flexunit] Suite: unitTests.button.ButtonTest
 [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
 [flexunit]
 [flexunit] Results :
 [flexunit]
 [flexunit] Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.004 sec
 [flexunit]

BUILD FAILED
```

(I confirm I have removed my local test files (to work within FB) prior the build)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I see some errors Tests run: 1, Failures: 0, Errors: 1, in each tests. Can you take a look into the reports it's generated inside bin folder as I remember. 

Is there anything more in the log terminal ?

**Comment by rat-moonshine** [comment]
Unfortunately, that was the end of the command-line output. I confirm I see many log/xml files under 'bin' folder, i.e. `TEST-unitTests.button.ButtonTest.xml`, however the content of the files are identical:

```
<?xml version="1.0" encoding="UTF-8"?>

<testsuite name="unitTests.converter.ConverterTest" tests="1" failures="0" errors="1" skipped="0" time="0.000" hostname="DESKTOP-OV6B35O" timestamp="2019-01-07T08:48:55">
  <testcase classname="unitTests.converter::ConverterTest" name="initializationError" time="0.000">
    <error message="There was an error retrieving the parameters for the testcase: cause Unable to load data tests" type="unitTests.converter::ConverterTest.initializationError"><![CDATA[]]></error>
  </testcase>
</testsuite>
```

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Can you progress for now without that ? I will look into that afternoon my time to see whether I can reproduce same thing.

**Comment by rat-moonshine** [comment]
Yes, I can proceed and this is not a blocker for me at this time. By the way, do we also want to evaluate components with multiple rows, i.e. SelectOneRadio with multiple items?

**Comment by piotrzarzycki21** [comment]
> Yes, I can proceed and this is not a blocker for me at this time. By the way, do we also want to evaluate components with multiple rows, i.e. SelectOneRadio with multiple items?

Well I was thinking about that, but let's leave it for now as is.

**Comment by rat-moonshine** [comment]
Hm... If I ran through FB (by adding only an windowed application MXML and its corresponding descriptor file), I do not get this error, tests ran successfully. I think the likewise error I have seen during tests in FB when XML file do not feed properly (wrong path etc.).

Okay, if this works on Bamboo (and at you), this might be some problem within my setup. Perhaps, we can debug this along with you at some time.

**Comment by piotrzarzycki21** [comment]
It looks like this XML is not running properly. What if you comment out this test from AllTestsSuite and run ant build?
Does Bamboo build is ready ? I haven't heard from Joel that he setup any ?

**Comment by rat-moonshine** [comment]
Which part in particular you want me to comment out and test? 

Joel did setup a Bamboo build for the CLI project, which pre-build VisualEditorConverterLib by its Ant build file; However, since the unit test Ant run opens a browser window and hang the process, he's running the Ant build by specific targets at this moment. 

I'll plan to install requisites to the build system and associate the SWF with the Flash Player, then I'll give a test to run with unit test targets too, at Bamboo.

**Comment by piotrzarzycki21** [comment]
Comment ConverterTest. Test in general do not open browser - they open Flash Player projector.

**Comment by rat-moonshine** [comment]
I'm not sure if I understood you correctly - but I have commented out [ConverterTest](https://github.com/prominic/VisualEditorConverterLib/blob/master/libTests/src/unitTests/AllTestsSuite.as#L37) line in `AllTestsSuite.as` file, but that didn't make any difference in Ant build process. 

I talked to @JoelProminic , he setup the requisite at his macOS system, but reported with similar errors as me.

**Comment by piotrzarzycki21** [comment]
Tomorrow I will try to run some tests on my Mac. Maybe I will reproduce that stuff. I'm wondering how bamboo can work with that.

**Comment by JoelProminic** [comment]
I setup the Flash Player Projector (not the debug version) on the macOS Bamboo remote agent:  https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.dmg

Bamboo has built-in support for test cases, though I'm not sure if it will work for FlexUnit.   We can try this once the test cases have been fixed.

**Comment by rat-moonshine** [comment]
> Tomorrow I will try to run some tests on my Mac. Maybe I will reproduce that stuff. I'm wondering how bamboo can work with that.

Bamboo build do not run unit test part at this moment, to overcome the current compilation problem.

**Comment by rat-moonshine** [comment]
> The problem was the leading slash on the URL: "/examples/button/button.xml". I updated "/examples/" to "examples/", and that resolved

Whoa! I remember I have seen path errors during Ant builds (in past) when any resource path set as 'resource/images/..' instead of '/resource/images..' - this was like how it suppose to does during Ant build. Thus, many of our embedding path command in ActionScript follows the slash-prefix way and that works. Maybe, since not-embedding case this might work differently, specially when SWF is running and tries to understand a path starts with slash.

**Comment by piotrzarzycki21** [comment]
@JoelProminic The reason why you have had that issue was that you probably didn't specify [direct path](https://github.com/prominic/VisualEditorConverterLib/blob/453252a8e43f3c8b15ba846512594bc2bf347640/libTests/src/config/TestConfig.as#L28) to folder where [examples](https://github.com/prominic/VisualEditorConverterLib/tree/master/libTests/src/examples) are stored. 
On Windows I'm putting there `d:\\projects\\VisualEditorConverterLib\\libTests\\src\\`, unfortunately on Mac I have no idea what to put in order to have it working. - I was trying to add there similar path but I got the same fail as you. 
Above settings in TestConfig class are mainly to satisfy IDE which for some reason during compilation cannot properly copy examples to output folder.
However I have pushed changes to build.xml which allows omit setup that path and ant should be able to run tests without the problem. - Let me know what are you seeing on bamboo.

**Comment by piotrzarzycki21** [comment]
> I setup the Flash Player Projector (not the debug version) on the macOS Bamboo remote agent: https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.dmg
> 
> Bamboo has built-in support for test cases, though I'm not sure if it will work for FlexUnit. We can try this once the test cases have been fixed.

I bet it's possible but it is required a bit of exercises. I think the most possible thing is not necessary run Flex tests, but display tests reports which are generated during run in bin folder. Bamboo probably have plugin to interpret Java tests reports. In [following example](https://flex.apache.org/flexunit/tutorial/flexunit/Unit-16.html) they are setup unit tests on Jenkins. If you download that example and go to file `FlexUnitCI/build.xml` you will see that they are translating Flex tests reports to JUnit style of reports. I have added [that part](https://github.com/prominic/VisualEditorConverterLib/blob/fd277e536df7b1a35cc4b1a5882a01cac294b5f5/build.xml#L65) to our build script as well. You can try to make something on bamboo with those reports, maybe you will get some nice visualization on bamboo thanks to this. JUnit reports are generated to` bin/html`.

**Comment by JoelProminic** [comment]
The tests run fine on my local machine after your update.   I still see two errors:

     [flexunit] Suite: unitTests.tabView.TabViewTest
     [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.000 sec
     ...
     [flexunit] Suite: unitTests.selectOneRadio.SelectOneRadioTest
     [flexunit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec
     [flexunit] 
     [flexunit] Results :
     [flexunit] 
     [flexunit] Tests run: 38, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.402 sec


TEST-unitTests.tabView.TabViewTest.xml

    <error message="There was an error retrieving the parameters for the testcase: cause Unable to load data tests [IOErrorEvent type=&quot;ioError&quot; bubbles=false cancelable=false eventPhase=2 text=&quot;Error #2032&quot;]" type="unitTests.tabView::TabViewTest.initializationError"><![CDATA[]]></error>


TEST-unitTests.selectOneRadio.SelectOneRadioTest.xml

    <error message="There was an error retrieving the parameters for the testcase: cause Unable to load data tests [IOErrorEvent type=&quot;ioError&quot; bubbles=false cancelable=false eventPhase=2 text=&quot;Error #2032&quot;]" type="unitTests.selectOneRadio::SelectOneRadioTest.initializationError"><![CDATA[]]></error>

**Comment by piotrzarzycki21** [comment]
@JoelProminic I just pushed changes which may fix both errors. Try it out.

**Comment by JoelProminic** [comment]
I made a couple minor updates to build.xml to get it to run properly on Bamboo.  Now that this is done, I confirmed that the test cases show up in Bamboo:

![image](https://user-images.githubusercontent.com/24532731/50857546-9a182e00-1353-11e9-975a-37f673157006.png)
![image](https://user-images.githubusercontent.com/24532731/50857555-a00e0f00-1353-11e9-8659-cf956f8e7077.png)

The Bamboo plan should fail if any of the tests fail.

**Comment by piotrzarzycki21** [comment]
Cool! Too bad that I don't have access to that :) Great to see it's working. Let's cover all components. :)

**Comment by rat-moonshine** [comment]
I also able to have the Ant build process complete this time without any overdo, on Windows. Thanks you for the changes, Piotr!

**Comment by piotrzarzycki21** [comment]
@rat-moonshine The only thing which left in case of tets unit is implementing [that tests](https://github.com/prominic/VisualEditorConverterLib/commit/fa0301e75fb9f6763b024174eefa9500e5d6bd29#r31879438) by you.

**Comment by rat-moonshine** [comment]
Yeh.. I was bit confused while adding both the test cases per the idea you had! Like, whether we need dual XMLs to support these tests etc. Do we have any dual tests already added which can be followed for such cases? The only case has with dual XMLs I found is for Button. But that may not fit exact this scenario. If you has the clear idea about this, can you create one such test scenario if not already exists?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine Yes you need another xml which doesn't contains text property. Copy existing one, name it appropriately and write tests. Example of such approach you have also in [SelectOneListboxTest](https://github.com/prominic/VisualEditorConverterLib/blob/master/libTests/src/unitTests/selectOneListbox/SelectOneListboxTest.as) and method [noValueTest](https://github.com/prominic/VisualEditorConverterLib/blob/6deae02e7b0cba6450234c452be43e4286863ec7/libTests/src/unitTests/selectOneListbox/SelectOneListboxTest.as#L120).

**Comment by rat-moonshine** [comment]
Well, when the static methods do called by the framework process, then we have to follow the design.

I have updated the TextEditor test cases with no-text test case, please check.

**Comment by piotrzarzycki21** [comment]
I think we are good with that task. More tests should come along with new features.
