### ISSUE TITLE
Git > Clone Issues With Manually Entered URL

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#525]
I noticed this behavior today:
1. Open Moonshine
2. Git > Clone
3. Manually type this repository URL:  https://github.com/prominic/Moonshine-IDE.git
4. BUG:  The Target folder name field is set to "p" once you start typing "prominic", and the value does not update after this
5. Try to type the project name in the "Target folder name" field.  BUG:  The '-' character is now allowed (an neither is '.' which would be be included in the string if you pasted the above URL.

This behavior is a minor annoyance.  I would expect it to wait until I finshed entering the URL to parse the value (this might trigger on focus change).  Alternatively the Target folder name could be updated each time to match the URL, unless the user made a manual entry or modification in Target folder name.

The character restrictions for Target folder name should match the restrictions for new projects.   The restrictions should also be applied to the project name extracted from the URL.

**Comment by rat-moonshine** [comment]
This should fixed now.

**Comment by piotrzarzycki21** [comment]
Are you waiting for Joel's review ? If not close that.

**Comment by rat-moonshine** [comment]
Yeh, we'll wait till Joel's review.

**Comment by JoelProminic** [comment]
The update logic works well for the Target folder name:
- Adding or removing characters in the URL updates Target folder name
- If I manually edit Target folder name, URL updates no longer change the Target folder name value.

I still see that the project name copied from the URL does not use the character restrictions for direct text entry into Target folder name (0-9A-Za-z_).   This does not affect the usability of the interface, so I will create another issue that can be updated in a later release.   We may want to unify the allowed characters for Moonshine projects or folders with the characters allowed for GitHub projects.
