### ISSUE TITLE
Haxe/Royale: Debugger for Chrome

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#643]

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have downloaded newest nightly build of Moonshine and tried to build our project with Royale [392](http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/392/) build. I'm getting following error:

```
: Internal error: java.lang.NullPointerException java.io.File.<init>(File.java:277)org.apache.royale.compiler.internal.codegen.js.JSWriter.convertSourcePathToURI(JSWriter.java:171)org.apache.royale.compiler.internal.codegen.js.JSWriter.convertMappingSourcePathsToURI(JSWriter.java:164)org.apache.royale.compiler.internal.codegen.mxml.MXMLWriter.writeTo(MXMLWriter.java:95)org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:414)org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:265)org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:222)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:369)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:304)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:262)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:244)
: 
```

Is it related to your latest changes in that area ? I don't get such error when I'm building our application using Maven.

**Comment by piotrzarzycki21** [comment]
I just tried build project on my Mac and there wasn't such problems. I was using non sandbox nightly build of Moonshine.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Building your project seems to be failing during the creation of source maps for one of your .mxml files. One of my changes to Moonshine was to add `--source-map=true` to the compiler options so that debugging in Chrome can use the original .mxml and .as files. It appears that the source map feature in the Royale compiler has a bug.

Do you think that you can try to figure out which of your .mxml files is causing the null pointer exception? Basically, start commenting things out until it builds successfully without the exception, and then try to narrow it down to the bare minimum code that causes the issue. If you can get it down to a simple enough example, I should be able to fix the bug in the Royale compiler.

**Comment by piotrzarzycki21** [comment]
We have 100 hundred mxml files in our project, so it will be difficult, but I will try ;)

**Comment by piotrzarzycki21** [comment]
@joshtynjala I was ended up with one mxml file in the project which causes issue. It is main file of the application. The weird thing is that I cannot reproduce issue in a simple hello world app with the same code. I will send you our project by email - it will contains one file and some other rather not so important. Project requires sources of puremvc so archive contains those as well. 

If you comment out function  `onAppComplete` - error will gone.

**Comment by piotrzarzycki21** [comment]
I know that probably your next step is to improve Royale debugger but wanted to point to observation:
1) When I do menu **Project** -> **Build & Run as JavaScript** - application is running and trying to launch debugger - which shouldn't happen - This menu should do building only.
2) When I'm trying to run debugger I get:
```
Command: C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Moonshine\elements\http-server\bin\http-server D:\Work\projects\Prominic.NET\MoonshineTests\ListBindingIssue\NewJavaScriptBrowserProject\bin\js-debug -p 3000
: Process error: internal/modules/cjs/loader.js:626
:     throw err;
:     ^
: 
: Error: Cannot find module 'C:\Program Files (x86)\Moonshine\elements\chrome-debug-adapter\out\src\chromeDebug.js'
:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
:     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
:     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
:     at internal/main/run_main_module.js:17:11 {
:   code: 'MODULE_NOT_FOUND',
:   requireStack: []
: }
: Debug adapter exited unexpectedly.
: HTTP server has been terminated.
```

**Comment by joshtynjala** [comment]
For consistency, "Build & Run as JavaScript" runs the debug adapter in non-debug mode. It ensures that Chrome is launched the same way for Run and Debug. It's potentially confusing if it launched Chrome to debug, but another (default) browser to Run.

Does "Build & Debug as JavaScript" work for you? The error you've shared would seem to indicate that both run and debug will fail because it is completely failing to find the debug adapter module.

**Comment by piotrzarzycki21** [comment]
Both options fail to me with the same error. How are you generating that adapter? I see JS project there with some package.json etc. - Are you building that and get in the results this JS file which is missing?

**Comment by joshtynjala** [comment]
I downloaded a pre-built version of the chrome-debug-adapter, but I see that it included a .gitignore file that resulted in some files not being added to the Moonshine-IDE repo. That should now be resolved.

**Comment by piotrzarzycki21** [comment]
> I downloaded a pre-built version of the chrome-debug-adapter, but I see that it included a .gitignore file that resulted in some files not being added to the Moonshine-IDE repo. That should now be resolved.

Thanks @joshtynjala ! I think something is failing on Bamboo. I asked @rat-moonshine to look into that - hopefully he will report here if it's connected to your commit.

**Comment by rat-moonshine** [comment]
I see macOS build completed successfully, so you should have that in nightly area. 

On Windows I see some error which probably requires some investigation. Here's the quick details to the error, if you found it rings any bell:

```
build	06-Jan-2020 17:35:08	CompileSWFWindowsSignedPackage:
build	06-Jan-2020 17:35:08	     [echo] Signed Process Running
build	06-Jan-2020 17:35:39	     [java] unexpected failure: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
build	06-Jan-2020 17:35:39	     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
build	06-Jan-2020 17:35:39	     [java] "
build	06-Jan-2020 17:35:39	     [java] java.io.IOException: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
build	06-Jan-2020 17:35:39	     [java] [ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
build	06-Jan-2020 17:35:39	     [java] "
build	06-Jan-2020 17:35:39	     [java] 	at com.adobe.air.nai.NativePackager.conversionFail(NativePackager.java:279)
build	06-Jan-2020 17:35:39	     [java] 	at com.adobe.air.nai.NativePackager.invokePlatformConversion(NativePackager.java:260)
build	06-Jan-2020 17:35:39	     [java] 	at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java:133)
build	06-Jan-2020 17:35:39	     [java] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java:673)
build	06-Jan-2020 17:35:39	     [java] 	at com.adobe.air.ADT.run(ADT.java:471)
build	06-Jan-2020 17:35:39	     [java] 	at com.adobe.air.ADT.main(ADT.java:521)
build	06-Jan-2020 17:35:39	     [java] Picked up _JAVA_OPTIONS: -Xmx1024M
error	06-Jan-2020 17:35:39	
error	06-Jan-2020 17:35:39	BUILD FAILED
error	06-Jan-2020 17:35:39	D:\bamboo-agent-home\xml-data\build-dir\MS-MGW-JOB1\Moonshine\ide\MoonshineSharedCore\build\build-lib.xml:209: The following error occurred while executing this line:
error	06-Jan-2020 17:35:39	D:\bamboo-agent-home\xml-data\build-dir\MS-MGW-JOB1\Moonshine\ide\MoonshineSharedCore\build\build-lib.xml:258: The following error occurred while executing this line:
error	06-Jan-2020 17:35:39	D:\bamboo-agent-home\xml-data\build-dir\MS-MGW-JOB1\Moonshine\ide\MoonshineSharedCore\build\build-lib.xml:264: Java returned: 5
error	06-Jan-2020 17:35:39	
error	06-Jan-2020 17:35:39	Total time: 2 minutes 40 seconds
```

**Comment by joshtynjala** [comment]
We had a similar issue previously: #379. Based on the comments there it may be that the full paths of some of the new files are too long.

That being said, I'm on Windows 10 (64-bit), and I have Flex SDK 4.16.1 with AIR 28. I am able to run _ide/MoonshineDESKTOPevolved/build/build.xml_ successfully.

**Comment by joshtynjala** [comment]
I tried moving my repo on my local file system from here:

```
C:\Users\josht\Development\Work\Prominic\Moonshine-IDE\
```

to here: 

```
C:\Users\josht\Development\Work\Prominic\this-is-a-very-long-folder-name-to-test-if-the-build-will-fail\Moonshine-IDE\
```

Unfortunately, that didn't seem to make a difference. I got an error copying the folder within Windows explorer, so the path should be long enough (using robocopy from the command line copied successfully, since it seems to be able to handle longer paths).

I tried in both PowerShell and cmd, just to be sure.

**Comment by joshtynjala** [comment]
I just tried a 32-bit JVM, instead of 64-bit, and that worked correctly on my system too.

openjdk 1.8.0_232

Which version of Java and which version of Windows is the build server using?

**Comment by joshtynjala** [comment]
I made the folder name even longer, and now, I can reproduce, even with JDK 11 64-bit.

this-is-a-very-long-folder-name-to-test-if-the-build-will-fail-this-is-a-very-long-folder-name-to-test-if-the-build-will-fail

Unfortunately, I'm not sure if this can be easily fixed.

---

Is there any chance that this path could be shortened on the build server? If it were in D:\Moonshine, for instance, that might be good enough.

```
D:\bamboo-agent-home\xml-data\build-dir\MS-MGW-JOB1\Moonshine\
```

---

Alternatively, it seems that Windows 10 can be configured to allow longer paths:

https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

However, if the build server is on an older version of Windows, that option won't be available.

**Comment by rat-moonshine** [comment]
The Windows build machine is running an Windows 7 and default Java 1.8.0_171 x64. I'm afraid how easier it could be to update the Windows version (depending on various aspects).

If moving the Moonshine's build to D:\MS-MGW-JOB1\Moonshine\.. is something should work with existing installations, then that might be considerable; However, @JoelProminic should advise on this better as this could have different implications/complexities.

**Comment by JoelProminic** [comment]
Unfortunately, `D:\bamboo-agent-home\` is the only part of the path I have control over. `\xml-data\build-dir\MS-MGW-JOB1\Moonshine\` is added by Bamboo.

I can look into extending the maximum path on the build server tomorrow.

**Comment by JoelProminic** [comment]
As @rat-moonshine reported, this is a Windows 7 server.  The option to bypass the maximum path length was first available in [Windows 10, version 1607](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#enable-long-paths-in-windows-10-version-1607-and-later).

Do you know which file exceeded the maximum length?  I checked the filesystem on Bamboo, and I didn't see any path longer than 230 characters.

To try to work around this for now, I changed the checked-out project name from "Moonshine" to "M".  This fixed the Ant script execution, but I'm getting some strange unrelated errors from Bamboo with the new artifact locations.

**Comment by joshtynjala** [comment]
I don't know which file it is exactly, but it's somewhere in _ide/MoonshineSharedCore/src/elements/chrome-debug-adapter_. Either in _out_ or _node_modules_. Those two folders were initially missing when I first committed the chrome-debug-adapter because it included an unexpected _.gitignore_ file, and the build started failing after I fixed that issue.

**Comment by piotrzarzycki21** [comment]
> but I'm getting some strange unrelated errors from Bamboo with the new artifact locations.

It means that it's still failing even that you change this name ?

**Comment by JoelProminic** [comment]
My fix yesterday fixed the errors from the Ant script.   However, Bamboo didn't like the process I used to change it, so I had to spend most of the afternoon fighting with it :(.

I finally have it fixed now.  The build number has reset, but I confirmed that the files were updated on moonshine-ide.com.

**Comment by joshtynjala** [comment]
Sorry for the trouble! Looking forward to hearing if the new Chrome debugger is working well for everyone.

**Comment by piotrzarzycki21** [comment]
@joshtynjala Today I have spent some time on try debugger. It's working nicely in Hello World type of app, but with our Royale application it doesn't work. I think it would be worth handle that case. Here is how it looks like. 
I'm building application with custom url which is being setup in right click on project **Settings** -> **Run** -> **Custom URL to Launch**. I don't wont to reveal here exact url, so I will use as an example: `https://dev.moonshine.com/moonshine/bin/js-debug/index.html`
I also don't build application to a standard location `bin ` folder, but to [XAMPP](https://www.apachefriends.org/index.html) www folder, where later I'm running application using local instance of Apache server. 
My application after build is being attached to following address: 
`:   http://127.0.0.1:3000`, but I need to run trough my custom url as I mentioned above.

**Comment by joshtynjala** [comment]
I think that the Chrome debug adapter supports a way to map URLs in source maps to a different location, so I may be able to support a custom server. I'll see what I can do.

**Comment by piotrzarzycki21** [comment]
> I think that the Chrome debug adapter supports a way to map URLs in source maps to a different location, so I may be able to support a custom server. I'll see what I can do.

If you will be able to do that - I think we have enough good stuff to make another release. :)

**Comment by joshtynjala** [comment]
@piotrzarzycki21 With my latest changes, when running **Build and Debug** on a Royale JS project, Moonshine will now check if a value is specified in **Custom URL to Launch**. If there is a custom URL, Moonshine won't start its own localhost:3000 server, and it will simply launch your URL in Chrome.

I also tried some custom values for the **JavaScript Output Path** that were outside of the project folder, and I can see that the compiler generates the correct relatives paths from the custom output path to the original *.as and *.mxml files in in the project folder.

Please give the latest changes a try, and let me know how well that works for you!

**Comment by piotrzarzycki21** [comment]
I have tried your changes today, but it's failed - cause our application has "resources" folder which needs to be copied after/during compilation. I will work on fixing that part and than try to test again.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have fixed problem with copying resources. Unfortunately when I'm running debugger with my custom url it doesn't work. I do see that buttons in UI are active, application running, but it doesn't stop on breakpoints. 
Debugger is working for simple hello world without custom url.

**Comment by joshtynjala** [comment]
Can you try a simple hello world with a custom URL? You'll need to use your XAMPP server or a different server, of course.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I'm not sure what was wrong, but it's working now ! :) We are good and have debugger for our app! Thank you!

**Comment by piotrzarzycki21** [comment]
I have added ability to on/off -source-map to Build Options for Royale projects.

**Comment by joshtynjala** [comment]
I made source-map enabled by default in new projects, since most people will want that.
